# Generated by Django 5.1.4 on 2025-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_chapter_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='uniq_lesson_order_per_chapter'),
        ),
    ]
