# Generated by Django 5.1.4 on 2025-08-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_alter_chapter_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
